## 문제 1.
문제: 모든 값이 0으로 2차원 배열 (5, 5) 만드세요.

In [3]:
import numpy as np

z = np.zeros([5,5])
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 문제 2.
임의의 3x3 크기의 배열을 생성하고 배열의 shape(모양), dtype(데이터 타입), 그리고 배열의 차원 수(ndim)를 출력하세요.

In [7]:
rnd = np.random.random([3,3])

print(rnd.shape)
print(rnd.dtype)
print(rnd.ndim)
print(rnd)

(3, 3)
float64
2
[[0.71295989 0.1127817  0.81176639]
 [0.75236619 0.97397211 0.26125121]
 [0.77695889 0.25844304 0.49122389]]


## 문제 3.
- 주어진 배열에서 아래와 같이 슬라이싱 하세요.
```
array([[ 5,  6],
       [ 9, 10]])
```

In [8]:
arr = np.arange(16).reshape(4, 4)
arr

arr[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])